-- require("lvim.lsp.manager").setup("tsserver")

-- lvim.lang.javascript.linters = {
--   {
--     exe = "eslint_d"
--   }
-- }
-- lvim.lang.javascript.formatters = {
--   {
--     exe = "prettierd"
--   }
-- }
