local M = {}

M.config = function()
  lvim.builtin.indentlines.options = {
    enabled = true,
    bufname_exclude = { "README.md" },
    buftypes = { "terminal", "nofile", "dashboard", "fugitive"  },
    filetype_exclude = {
      "LuaTree",
      "NvimTree",
      "Outline",
      "TelescopePrompt",
      "Trouble",
      "UltestOutput",
      "UltestSummary",
      "alpha",
      "dapui_breakpoints",
      "dapui_hover",
      "dapui_scopes",
      "dapui_stacks",
      "dapui_watches",
      "dashboard",
      "dbui",
      "flutterToolsOutline",
      "fugitive",
      "git",
      "gitcommit",
      "help",
      "json",
      "lazy",
      "log",
      "lsp-installer",
      "lspinfo",
      "markdown",
      "neogitstatus",
      "org",
      "orgagenda",
      "packer",
      "startify",
      "terminal",
      "txt",
      "undotree",
      "vimwiki",
      "vista",
      "", -- for all buffers without a file type
    },
    -- char = "▏",
    char_list = { "", "┊", "┆", "¦", "|", "¦", "┆", "┊", "" },
    char_highlight_list = {
      "IndentBlanklineIndent1",
      "IndentBlanklineIndent1",
      "IndentBlanklineIndent1",
      "IndentBlanklineIndent1",
      "IndentBlanklineIndent1",
      "IndentBlanklineIndent1",
    },
    show_trailing_blankline_indent = false,
    show_first_indent_level = false,
    space_char_blankline = " ",
    use_treesitter = true,
    show_foldtext = false,
    show_current_context = true,
    show_current_context_start = false,
    context_patterns = {
      "class",
      "return",
      "function",
      "method",
      "^if",
      "^do",
      "^switch",
      "^while",
      "jsx_element",
      "^for",
      "^object",
      "^table",
      "block",
      "arguments",
      "if_statement",
      "else_clause",
      "jsx_element",
      "jsx_self_closing_element",
      "try_statement",
      "catch_clause",
      "import_statement",
      "operation_type",
    },
  }
end

return M
